- .github/workflows/deploy.yml
- .idea/.gitignore
- .idea/WBE4_5_SukChanHoSu_BE.iml
- .idea/git_toolbox_blame.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
ci 환경구성
---
- 예시:
- test, main merge 시 ghcr 이미지 빌드 및 생성
---
---
---
---
> docs/ci 환경구성#4

- .github/workflows/deploy.yml
> deploy directory 변경
---
- 예시:
- 디렉토리 경로 수정
---
---
---
---
> docs/deploy directory 변경

- .github/workflows/deploy.yml
> deploy directory 재변경
---
- 예시:
- deploy directory 재변경
---
---
---
---
> docs/deploy directory 재변경

- backend/build.gradle
> gradle mysql 의존성 추가)
---
- gradle mysql 의존성 추가
---
---
---
---
> docfeat/gradle mysql 의존성 추가

- .github/workflows/deploy.yml
- backend/build.gradle
> deploy 설정변경
---
- deploy 설정변경
---
---
---
---
> docs/deploy 설정변경

- backend/build.gradle
>의존성 수정
---
- 의존성 수정
---
---
---
---
> feat/ 의존성 수정

- .idea/WBE4_5_SukChanHoSu_BE.iml
- .idea/misc.xml
> application-secret 생성
---
- application-secret 생성
---
---
---
---
> application-secret 생성

- backend/src/main/resources/application.yml
> application.yml 수정
---
- application.yml 수정
---
---
---
---
> feat/application.yml 수정

- .github/workflows/deploy.yml
- .idea/libraries/gradle_wrapper.xml
- .idea/vcs.xml
- backend/Dockerfile
- backend/src/main/resources/application-test.yml
- out/production/WBE4_5_SukChanHoSu_BE/main/resources/application-test.yml
- out/production/WBE4_5_SukChanHoSu_BE/main/resources/application.yml
> db설정, pr시 actions적용
---
- db설정, pr시 actions적용
---
---
---
---
> docs/ db설정, pr시 actions적용

- .github/workflows/deploy.yml
- backend/Dockerfile
- backend/build.gradle
- backend/src/main/resources/application.yml
> docs/deploy 수정
---
- docs/deploy 수정
---
---
---
---
> docs/deploy 수정

- .github/workflows/deploy.yml
> deploy 작업흐름 변경
---
- 예시:
---
---
---
---
> chore: deploy 작업흐름 변경

- backend/build.gradle
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/email/config/EmailConfig.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/email/controller/EmailController.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/email/dto/request/EmailDto.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/email/service/EmailService.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/entity/User.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/entity/UserErrorCode.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/entity/UserSuccessCode.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/security/SecurityConfig.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/application.yml
- 회원가입 후 이메일 인증을 위한 메일 전송
---
- 회원가입 후 이메일 인증을 위한 메일 전송
---
#76 
---
> feat: 회원가입 후 인증코드 이메일로 전송 기능 구현

- .github/workflows/deploy.yml
- backend/src/main/resources/application-dev.yml
> deploy 수정
---
- deploy 수정
---
---
---
---
> chore: deploy 수정

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/controller/UserLikeController.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/controller/UserProfileController.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/entity/User.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/entity/UserProfile.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/service/UserLikeService.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/exception/redis/RedisSerializationException.java
- backend/src/test/java/com/NBE4_5_SukChanHoSu/BE/domain/User/controller/UserLikeControllerTest.java
- backend/src/test/java/com/NBE4_5_SukChanHoSu/BE/domain/User/controller/UserProfileControllerTest.java
- Param -> ContenxtHolder 사용
---
- 예시:
---
---
---
---
> Refactor/context holder/#75

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/security/SecurityConfig.java
cors 오류 해결
---
cors 오류 해결
1. 허용 도메인 지정해서 열어 놓기
2. 1번 안되면 모든 도메인 허용으로 변경 예정
3. 모든 헤더 허용
---
#95 
---
> refactor: CORS 오류 해결

- backend/node_modules/.package-lock.json
- backend/node_modules/k6/package.json
- backend/scripts/EventTest.js
- backend/scripts/LikeTest.js
- backend/scripts/MovieTest.js
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/init/BaseInitData.java
- backend/src/main/resources/application-dev.yml
> test: like,sse 부하 테스트

- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/application.yml
> fix:region

- .github/workflows/deploy.yml
> hotfix: main 브랜치시 배포로 변경

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/interceptor/ProfileCheckInterceptor.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/application.yml
무비 api 전체 락품(프로필등록전에도 접근가능)
- 예시:
---
---
---
---
> Hotfix userprofilelock

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/service/UserService.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/util/CookieUtil.java
- 토큰 주기, 쿠키 도메인 설정
---
- 토큰 주기 증가
- 쿠키 도메인 배포 서버로 저장
---
#147 
---
> refactor: 상수화 및 불필요 메서드 제거

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/jwt/service/TokenService.java
- 불필요 코드 제거
---
- 불필요 코드 제거
---
#147 
---
> refactor: 불필요 라이브러리 제거

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/service/UserService.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/util/SecurityUtil.java
- 만료 기간 수정 및 리펙토링
---
- 만료 기간 수정 및 리펙토링
---
#154 
---
> refactor: 불필요 라이브러리, 메서드 제거

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/controller/UserProfileController.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/service/UserProfileService.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/interceptor/ProfileCheckInterceptor.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/security/SecurityConfig.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/NBE4_5_SukChanHoSu/BE/domain/user/service/UserProfileServiceTest.java
이미지 등록이랑, dto request   <-  api 쪼갬(create,update둘다)
- 예시:
---
---
---
---
> hotfix:seperate api

- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/controller/TokenController.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/domain/user/controller/UserController.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/security/OAuth2AuthenticationSuccessHandler.java
- backend/src/main/java/com/NBE4_5_SukChanHoSu/BE/global/util/CookieUtil.java
- 쿠키 도메인 동적 할당
---
- - 쿠키 도메인 동적 할당
---
#157 
---
> refactor: 쿠키 도메인 동적으로 할당

- backend/src/main/resources/application-prod.yml
- infra/main.tf
> feat: 환경변수 추가
